/**
 * Search keywords derived from the Emerge soul document — ALL dimensions.
 * Used by city-based scrapers (Meetup, Eventbrite) to find regenerative events.
 */

/** Full soul document keyword set across all dimensions */
export const KEYWORDS: string[] = [
  // Land & Nature
  'permaculture',
  'food forest',
  'community garden',
  'seed swap',
  'natural building',
  'rewilding',
  'habitat restoration',
  'foraging',
  'wild food',
  'gleaning',
  'apple pressing',
  'wassail',

  // Circular & Repair
  'repair cafe',
  'tool library',
  'zero waste',
  'clothing swap',
  'fermentation',
  'sourdough',
  'composting',

  // Community & Economy
  'transition town',
  'solidarity economy',
  'time bank',
  'doughnut economics',
  'degrowth',
  'community kitchen',
  'disco soup',
  'community land trust',
  'ecocide law',
  'ecocide',
  'localisation',

  // Arts & Theatre
  'theatre of the oppressed',
  'forum theatre',
  'playback theatre',
  'community choir',
  'singing circle',
  'drum circle',

  // Wellness & Inner
  'ecotherapy',
  'forest bathing',
  'climate grief',
  'work that reconnects',
  'birth circle',
  'postnatal circle',

  // Energy & Infrastructure
  'community energy',
  'ecovillage',
  'regenerative agriculture',
  'agroforestry',

  // German keywords
  'Permakultur',
  'Lebensmittelwald',
  'Saatguttausch',
  'Naturbauen',
  'Null Abfall',
  'Forumtheater',
  'Theater der Unterdrückten',
  'Playback Theater',
  'Gemeinschaftschor',
  'Trommelkreis',
  'Ökotherapie',
  'Klimatrauer',
  'Geburtskreis',
  'Gemeinschaftsküche',
  'Disco Suppe',
  'Solidarische Ökonomie',
  'Stadtimkerei',
  'Kompost',
  'Wildpflanzen',
  'Solidarische Landwirtschaft',
  'Waldgarten',
  'Schnippeldisko',
  'Lokalisierung',
  'Gemeinschaftsgarten',
  'Ökozid',

  // French keywords
  'forêt comestible',
  'échange de semences',
  'construction naturelle',
  'zéro déchet',
  'théâtre de l\'opprimé',
  'théâtre forum',
  'playback théâtre',
  'chorale communautaire',
  'cercle de tambour',
  'écothérapie',
  'deuil climatique',
  'cercle de naissance',
  'cuisine communautaire',
  'disco soupe',
  'économie solidaire',
  'décroissance',
  'glanage',
  'plantes sauvages',
  'terre de liens',
  'banque du temps',
  'économie du donut',
  'AMAP',
  'incroyables comestibles',

  // Welsh keywords
  'permadhiwylliant',
  'trawsnewid',
  'coedwig fwyd',
  'cyfnewid hadau',
  'adeiladu naturiol',
  'caffi atgyweirio',
  'dim gwastraff',
  'theatr y gorthrymedig',
  'côr cymunedol',
  'ecoterapi',
  'galar hinsawdd',
  'cylch geni',
  'cegin gymunedol',
  'economi undod',
  'adfer bywyd gwyllt',
  'lloffa',
  'bwyd gwyllt',
  'lleoleiddio',

  // Irish keywords
  'péirmacultúr',
  'aistriú',
  'coill bia',
  'malartú síolta',
  'tógáil nádúrtha',
  'nialas dramhaíola',
  'cór pobail',
  'éiceteiripe',
  'ciorcal breithe',
  'cistin phobail',
  'geilleagar dlúthpháirtíochta',
  'gliúcaireacht',
  'coipeadh',
  'bia fiáin',
  'éicídé',

  // Maltese keywords
  'tranżizzjoni',
  'foresta tal-ikel',
  'skart żero',
  'teatru tal-maħkumin',
  'kor tal-komunità',
  'ekoterapija',
  'kċina tal-komunità',
  'ekonomija solidali',
  'ikel selvaġġ',
  'ekoċidju',

  // Danish keywords
  'omstilling',
  'madkovskov',
  'frøbytte',
  'naturbyggeri',
  'nul affald',
  'de undertryktes teater',
  'fællessang',
  'økoterapi',
  'klimasorg',
  'fødselscirkel',
  'fælles køkken',
  'solidaritetsøkonomi',
  'genopretning',
  'vilde urter',
  'økolandsby',
  'lokalisering',

  // Finnish keywords
  'permakultuuri',
  'siirtymä',
  'ruokametsä',
  'siemenvaihtotapahtuma',
  'luonnonmukainen rakentaminen',
  'korjauskahvila',
  'nollapäästö',
  'sorrettujen teatteri',
  'yhteisökuoro',
  'ekoterapia',
  'ilmastosurutyö',
  'syntymäpiiri',
  'yhteisökeittiö',
  'solidaarisuustalous',
  'ennallistaminen',
  'talkoot',
  'villiruoka',
  'lokalisaatio',

  // Italian keywords
  'transizione',
  'foresta del cibo',
  'scambio semi',
  'costruzione naturale',
  'rifiuti zero',
  'teatro degli oppressi',
  'teatro forum',
  'teatro playback',
  'coro comunitario',
  'cerchio di tamburi',
  'lutto climatico',
  'cerchio nascita',
  'cucina comunitaria',
  'disco zuppa',
  'economia solidale',
  'decrescita',
  'spigolatura',
  'pasta madre',
  'piante selvatiche',
  'economia della ciambella',
  'banca del tempo',
  'GAS gruppo acquisto',

  // Spanish keywords
  'permacultura',
  'transición',
  'bosque comestible',
  'intercambio semillas',
  'construcción natural',
  'cero residuos',
  'teatro del oprimido',
  'teatro foro',
  'teatro playback',
  'coro comunitario',
  'círculo de tambores',
  'ecoterapia',
  'duelo climático',
  'círculo de nacimiento',
  'cocina comunitaria',
  'sopa disco',
  'economía solidaria',
  'decrecimiento',
  'espigueo',
  'masa madre',
  'plantas silvestres',
  'ecocidio',
  'economía del donut',
  'banco del tiempo',

  // Additional English
  'mutual aid',

  // Dutch keywords
  'permacultuur',
  'voedselbosbouw',
  'zaadruil',
  'natuurlijk bouwen',
  'nul afval',
  'forumtheater',
  'speeltheater',
  'gemeenschapskoor',
  'trommelcirkel',
  'ecotherapie',
  'klimaatrouw',
  'geboortecirkel',
  'gemeenschapskeukens',
  'disco soep',
  'solidaire economie',
  'stadslandbouw',
  'composteren',
  'fermentatie',
  'zuurdesem',
  'wilde planten',

  // Scots Gaelic keywords
  'permacultar',
  'coille-bìdh',
  'iomlaid sìl',
  'còisir choimhearsnachd',
  'ath-fhiadhachadh',
  'coimhearsnachd fearainn',
  'eag-olaigheachd',

  // Icelandic keywords
  'permabygging',
  'umbreyting',
  'matarskógur',
  'fræskipti',
  'náttúrulegt byggingarfræði',
  'núll sorp',
  'leikhús kúgaðra',
  'samfélagskór',
  'vistmeðferð',
  'loftslagssorg',
  'fæðingarhrings',
  'samfélagseldhús',
  'samstæðuhagkerfi',
  'endurreisn náttúru',
  'villt matur',
  'staðbinding',

  // Serbian keywords
  'permakultura',
  'tranzicija',
  'šuma hrane',
  'razmena semena',
  'prirodna gradnja',
  'nula otpada',
  'pozorište potlačenih',
  'forum teatar',
  'zajednički hor',
  'ekoterapija',
  'klimatska tuga',
  'krug rađanja',
  'zajednička kuhinja',
  'solidarna ekonomija',
  'obnova divljine',
  'fermentacija',
  'divlja hrana',
  'lokalizacija',

  // Slovenian keywords
  'prehod',
  'prehranska gozd',
  'izmenjava semen',
  'naravna gradnja',
  'nič odpadkov',
  'gledališče zatiranih',
  'skupnostni zbor',
  'podnebna žalost',
  'rojstni krog',
  'skupnostna kuhinja',
  'solidarnostno gospodarstvo',
  'ponovitev divjine',
  'divja hrana',

  // Diaspora cultural feast keywords
  'Nowruz', 'community iftar', 'open iftar', 'Eid celebration',
  'Diwali feast', 'Lunar New Year feast', 'community feast',
  'cultural potluck', 'Caribbean feast', 'African dinner community',
  'harvest supper', 'Disco Soup', 'street feast', 'community dinner',
  'Imbolc feast', 'solstice feast',

  // Hungarian keywords
  'átmenet',
  'ételerdő',
  'magcsere',
  'természetes építés',
  'zero hulladék',
  'elnyomottak színháza',
  'fórum színház',
  'közösségi kórus',
  'ökoterápia',
  'klímasmárás',
  'szülési kör',
  'közösségi konyha',
  'szolidáris gazdaság',
  'vadon visszaállítása',
  'erjesztés',
  'vadételek',
  'lokalizáció',

  // Participatory Music (Play)
  'folk session',
  'jam session',
  'drum circle',
  'balfolk',
  'open mic community',
  'traditional music session',
  'shape note singing',
  'Sacred Harp singing',
  'music workshop free',
  'community jam',
  'singing circle',
  'community choir free',
  'rhythm workshop',
  'Irish trad session',
  'community drumming',
  // UK Play
  'singing session',
  'ceilidh community',
  'wassail',
  'shanty session',
  // Irish Play
  'irish session',
  'trad session',
  'céilí',
  'set dancing',
  'open session',
  'singaround',
  'community choir open',
  'bodhrán workshop',
  'fiddle workshop open',
  'sean-nós community',
  // German Play
  'Folkabend',
  'Irische Session',
  'Trommelkreis',
  'offene Jamsession',
  'Gemeinschaftschor offen',
  'Folk Workshop',
  'Volksmusik Session',
  'Singrunde',
  'Shanty Session',
  'offenes Singen',
  'Musik Workshop kostenlos',
  // Portuguese Play
  'sessão de fado comunitária',
  'círculo de percussão',
  'música tradicional portuguesa',
  'rancho folclórico aberto',
  'oficina de música',
  'viola campaniça',
  'cante alentejano comunitário',
  'open mic comunitário',
  'música ao vivo gratuita',

  // Ecological & Community Art (Make)
  'open studio',
  'community mural',
  'ecological art',
  'land art',
  'climate art',
  'artist residency open',
  'art workshop community',
  'zine making',
  'printmaking community',
  'participatory art',
  'community photography',
  'collective textile',
  'art collective open',
  'eco art walk',
  'climate witness art',
  // UK Make
  'screen printing community',
  'artist-led walk',
  'art workshop free',
  'climate art open',
  // Irish Make
  'arts council community project',
  'printmaking open',
  'community darkroom',
  'artist residency open day',
  'art walk community',
  // German Make
  'Offenes Atelier',
  'Gemeinschaftswandgemälde',
  'ökologische Kunst',
  'Klimakunst',
  'Kunstkollektiv offen',
  'Druckwerkstatt',
  'Siebdruck Gemeinschaft',
  'Zine Workshop',
  'Künstlerresidenz offen',
  'Kunstspaziergang',
  'partizipative Kunst',
  // Portuguese Make
  'estúdio aberto',
  'mural comunitário',
  'arte ecológica',
  'arte e natureza',
  'exposição comunitária',
  'atelier aberto',
  'arte colaborativa',
  'impressão comunitária',
  'arte climática',
  'residência artística aberto',
  'espaço alternativo',
]

/**
 * Max keywords to use per city for Meetup/Eventbrite searches.
 * Full set is used — rate limiting handles the volume.
 */
export const MAX_KEYWORDS_PER_CITY = 420
